import SwiftUI
import UIKit

/// An explicit command, never generated by passive scroll-position reports.
public struct ReaderPageJump: Equatable {
    let id = UUID()
    let page: Int
}

public struct WebtoonZoomContainer: UIViewRepresentable {
    let urls: [String]
    let initialPage: Int
    let jump: ReaderPageJump?
    let onPageChange: (Int) -> Void
    let onSingleTap: () -> Void

    public func makeUIView(context: Context) -> WebtoonZoomHostView {
        WebtoonZoomHostView()
    }

    public func updateUIView(_ uiView: WebtoonZoomHostView, context: Context) {
        uiView.onPageChange = onPageChange
        uiView.onSingleTap = onSingleTap
        uiView.configure(urls: urls, initialPage: initialPage, jump: jump)
    }

    public static func dismantleUIView(_ uiView: WebtoonZoomHostView, coordinator: ()) {
        uiView.stopLoading()
        uiView.onPageChange = { _ in }
        uiView.onSingleTap = {}
    }
}

/// One UIScrollView owns both pan and pinch. Only its content is zoomed;
/// the viewport is never transformed. Page views stay near the viewport.
public final class WebtoonZoomHostView: UIView, UIScrollViewDelegate, UIGestureRecognizerDelegate {
    var onPageChange: (Int) -> Void = { _ in }
    var onSingleTap: () -> Void = {}

    private let scrollView = UIScrollView()
    private let canvas = UIView()
    private var urls: [String] = []
    private var ratios: [Int: CGFloat] = [:]
    private var pendingRatios: [Int: CGFloat] = [:]
    private var frames: [CGRect] = []
    private var pages: [Int: ReaderImagePage] = [:]
    private var requests: [Int: Task<Void, Never>] = [:]
    private var generation = UUID()
    private var lastJump: UUID?
    private var pendingJump: Int?
    private var lastReportedPage: Int?
    private var viewportSize: CGSize = .zero
    private var layingOut = false
    private var zoomAnimating = false
    private var reportScheduled = false

    public override init(frame: CGRect) {
        super.init(frame: frame)
        backgroundColor = .black
        scrollView.backgroundColor = .black
        scrollView.delegate = self
        scrollView.minimumZoomScale = 1
        scrollView.maximumZoomScale = 5
        scrollView.contentInsetAdjustmentBehavior = .never
        scrollView.showsVerticalScrollIndicator = false
        scrollView.showsHorizontalScrollIndicator = false
        scrollView.alwaysBounceVertical = true
        scrollView.accessibilityIdentifier = "continuousReader"
        canvas.layer.anchorPoint = .zero
        scrollView.addSubview(canvas)
        addSubview(scrollView)

        let doubleTap = UITapGestureRecognizer(target: self, action: #selector(doubleTapped(_:)))
        doubleTap.numberOfTapsRequired = 2
        doubleTap.delegate = self
        scrollView.addGestureRecognizer(doubleTap)
        let singleTap = UITapGestureRecognizer(target: self, action: #selector(singleTapped))
        singleTap.require(toFail: doubleTap)
        singleTap.delegate = self
        scrollView.addGestureRecognizer(singleTap)
    }

    required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }

    func configure(urls newURLs: [String], initialPage: Int, jump: ReaderPageJump?) {
        if urls != newURLs {
            let oldAnchor = captureAnchor()
            let sameBook = !urls.isEmpty && !newURLs.isEmpty && urls.first == newURLs.first
            let oldURLs = urls
            stopLoading()
            urls = newURLs
            // Retain measured heights when the server updates the page count.
            ratios = ratios.filter { index, _ in
                oldURLs.indices.contains(index) && newURLs.indices.contains(index)
                    && oldURLs[index] == newURLs[index]
            }
            pendingRatios.removeAll()
            for page in pages.values { page.removeFromSuperview() }
            pages.removeAll()
            lastReportedPage = nil
            if !sameBook {
                // A newly mounted reader starts at the current page, not an old
                // slider command retained across a PAGE -> SCROLL mode switch.
                lastJump = jump?.id
                layingOut = true
                scrollView.setZoomScale(1, animated: false)
                layingOut = false
                pendingJump = clampPage(initialPage)
            } else if let target = pendingJump {
                pendingJump = clampPage(target)
            }
            rebuildLayout(anchor: sameBook ? oldAnchor : nil)
        }
        if let jump, jump.id != lastJump {
            lastJump = jump.id
            pendingJump = clampPage(jump.page)
            // Explicit jumps stop inertia. Passive page reports never come here.
            scrollView.setContentOffset(scrollView.contentOffset, animated: false)
            applyPendingJump()
        }
        updateVisiblePages()
    }

    func stopLoading() {
        generation = UUID()
        for task in requests.values { task.cancel() }
        requests.removeAll()
    }

    public override func layoutSubviews() {
        super.layoutSubviews()
        guard bounds.width > 0, bounds.height > 0, !layingOut else { return }
        if viewportSize != bounds.size {
            let anchor = captureAnchor()
            viewportSize = bounds.size
            layingOut = true
            scrollView.frame = bounds
            layingOut = false
            rebuildLayout(anchor: anchor)
        }
    }

    private struct Anchor {
        let page: Int
        let fraction: CGFloat
        let horizontalFraction: CGFloat
    }

    private func captureAnchor() -> Anchor? {
        guard !frames.isEmpty, canvas.bounds.width > 0 else { return nil }
        let scale = max(scrollView.zoomScale, 0.01)
        let y = max(0, scrollView.contentOffset.y / scale)
        let page = pageIndex(at: y)
        return Anchor(page: page,
                      fraction: min(1, max(0, (y - frames[page].minY) / frames[page].height)),
                      horizontalFraction: (scrollView.contentOffset.x + scrollView.bounds.width / 2)
                        / scale / canvas.bounds.width)
    }

    private var interacting: Bool {
        scrollView.isTracking || scrollView.isDragging || scrollView.isDecelerating
            || scrollView.isZooming || scrollView.isZoomBouncing || zoomAnimating
    }

    private func rebuildLayout(anchor: Anchor?) {
        guard viewportSize.width > 0, !layingOut else { return }
        layingOut = true
        let width = viewportSize.width
        var y: CGFloat = 0
        frames = urls.indices.map { index in
            let height = max(1, width * (ratios[index] ?? 1.4))
            defer { y += height }
            return CGRect(x: 0, y: y, width: width, height: height)
        }
        // Never assign frame to a transformed view. UIScrollView owns its
        // transform; unscaled bounds and position describe the whole document.
        canvas.bounds = CGRect(x: 0, y: 0, width: width, height: y)
        canvas.layer.position = .zero
        let scale = scrollView.zoomScale
        scrollView.contentSize = CGSize(width: width * scale, height: y * scale)
        for (index, page) in pages where frames.indices.contains(index) {
            page.frame = frames[index]
        }
        if let anchor, frames.indices.contains(anchor.page) {
            scrollView.contentOffset = clamped(CGPoint(
                x: anchor.horizontalFraction * width * scale - viewportSize.width / 2,
                y: (frames[anchor.page].minY + frames[anchor.page].height * anchor.fraction) * scale))
        } else {
            scrollView.contentOffset = clamped(scrollView.contentOffset)
        }
        layingOut = false
        applyPendingJump()
        updateVisiblePages()
    }

    private func clamped(_ point: CGPoint) -> CGPoint {
        CGPoint(x: min(max(0, point.x), max(0, scrollView.contentSize.width - scrollView.bounds.width)),
                y: min(max(0, point.y), max(0, scrollView.contentSize.height - scrollView.bounds.height)))
    }

    private func clampPage(_ page: Int) -> Int { min(max(0, page), max(0, urls.count - 1)) }

    private func pageIndex(at y: CGFloat) -> Int {
        var low = 0
        var high = frames.count
        while low < high {
            let mid = (low + high) / 2
            if frames[mid].maxY <= y { low = mid + 1 } else { high = mid }
        }
        return min(low, max(0, frames.count - 1))
    }

    private func applyPendingJump() {
        guard let page = pendingJump, frames.indices.contains(page), !layingOut else { return }
        layingOut = true
        scrollView.contentOffset = clamped(CGPoint(x: scrollView.contentOffset.x,
                                                   y: frames[page].minY * scrollView.zoomScale))
        layingOut = false
        // Keep the requested top anchored until this page's real height arrives.
        if ratios[page] != nil { pendingJump = nil }
    }

    private func updateVisiblePages() {
        guard !layingOut, !frames.isEmpty, viewportSize.height > 0 else { return }
        let scale = max(0.01, scrollView.zoomScale)
        let top = max(0, scrollView.contentOffset.y / scale)
        let bottom = (scrollView.contentOffset.y + viewportSize.height) / scale
        let first = pageIndex(at: top)
        let last = pageIndex(at: bottom)
        let range = max(0, first - 1)...min(urls.count - 1, last + 2)
        for index in Array(pages.keys) where !range.contains(index) {
            pages.removeValue(forKey: index)?.removeFromSuperview()
            requests.removeValue(forKey: index)?.cancel()
        }
        for index in range where pages[index] == nil {
            let page = ReaderImagePage()
            page.tag = index
            page.accessibilityIdentifier = "readerPage.\(index)"
            page.frame = frames[index]
            page.retry = { [weak self, weak page] in
                page?.failed = false
                self?.updateVisiblePages()
            }
            canvas.addSubview(page)
            pages[index] = page
        }
        // Visible pages before prefetch, at most three concurrent loads.
        let priority = Array(first...last) + Array(range).filter { $0 < first || $0 > last }
        for index in priority where requests.count < 3 {
            guard let page = pages[index], page.imageView.image == nil,
                  !page.failed, requests[index] == nil else { continue }
            loadPage(index)
        }
        schedulePageReport()
    }

    private func loadPage(_ index: Int) {
        let urlString = urls[index]
        let requestGeneration = generation
        requests[index] = Task { @MainActor [weak self] in
            do {
                let image: UIImage
                if let cached = await ImageCacheManager.shared.image(for: urlString) {
                    image = cached
                } else {
                    guard let url = URL(string: urlString) else { throw URLError(.badURL) }
                    let (data, response) = try await URLSession.shared.data(from: url)
                    guard let http = response as? HTTPURLResponse, (200..<300).contains(http.statusCode),
                          let decoded = UIImage(data: data), decoded.size.width > 0,
                          decoded.size.height > 0 else { throw URLError(.cannotDecodeContentData) }
                    try Task.checkCancellation()
                    await ImageCacheManager.shared.store(image: decoded, data: data, for: urlString)
                    image = decoded
                }
                let displayImage = await image.byPreparingForDisplay() ?? image
                try Task.checkCancellation()
                guard let self, self.generation == requestGeneration, let page = self.pages[index] else { return }
                self.requests[index] = nil
                page.show(displayImage)
                self.pendingRatios[index] = image.size.height / max(1, image.size.width)
                self.commitImageSizesIfIdle()
                self.updateVisiblePages()
            } catch {
                guard !Task.isCancelled, let self, self.generation == requestGeneration else { return }
                self.requests[index] = nil
                self.pages[index]?.failed = true
                if self.pendingJump == index { self.pendingJump = nil }
                self.updateVisiblePages()
            }
        }
    }

    private func commitImageSizesIfIdle() {
        guard !interacting, !pendingRatios.isEmpty else { return }
        let anchor = captureAnchor()
        ratios.merge(pendingRatios) { _, new in new }
        pendingRatios.removeAll()
        UIView.performWithoutAnimation { rebuildLayout(anchor: anchor) }
    }

    private func schedulePageReport() {
        guard !reportScheduled else { return }
        reportScheduled = true
        // Defer SwiftUI binding writes out of updateUIView/layout callbacks.
        DispatchQueue.main.async { [weak self] in
            guard let self else { return }
            self.reportScheduled = false
            guard !self.frames.isEmpty else { return }
            let y = (self.scrollView.contentOffset.y + self.viewportSize.height * 0.5)
                / max(0.01, self.scrollView.zoomScale)
            let page = self.pendingJump ?? self.pageIndex(at: y)
            guard page != self.lastReportedPage else { return }
            self.lastReportedPage = page
            self.onPageChange(page)
        }
    }

    public func viewForZooming(in scrollView: UIScrollView) -> UIView? { canvas }
    public func scrollViewDidScroll(_ scrollView: UIScrollView) { updateVisiblePages() }
    public func scrollViewDidZoom(_ scrollView: UIScrollView) { updateVisiblePages() }
    public func scrollViewWillBeginDragging(_ scrollView: UIScrollView) { pendingJump = nil }
    public func scrollViewWillBeginZooming(_ scrollView: UIScrollView, with view: UIView?) { pendingJump = nil }
    public func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool) {
        if !decelerate { commitImageSizesIfIdle() }
    }
    public func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) { commitImageSizesIfIdle() }
    public func scrollViewDidEndZooming(_ scrollView: UIScrollView, with view: UIView?, atScale scale: CGFloat) {
        zoomAnimating = false
        commitImageSizesIfIdle()
        updateVisiblePages()
    }

    public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
        var view = touch.view
        while let current = view, current !== scrollView {
            if current is UIControl { return false }
            view = current.superview
        }
        return true
    }

    @objc private func singleTapped() { onSingleTap() }

    @objc private func doubleTapped(_ gesture: UITapGestureRecognizer) {
        toggleZoom(at: gesture.location(in: canvas))
    }

    func toggleZoom(at point: CGPoint) {
        pendingJump = nil
        let target: CGFloat = scrollView.zoomScale > 1.05 ? 1 : 2.5
        let size = CGSize(width: scrollView.bounds.width / target, height: scrollView.bounds.height / target)
        let rect = CGRect(x: point.x - size.width / 2, y: point.y - size.height / 2,
                          width: size.width, height: size.height)
        zoomAnimating = true
        scrollView.zoom(to: rect, animated: true)
    }
}

private final class ReaderImagePage: UIView {
    let imageView = UIImageView()
    private let spinner = UIActivityIndicatorView(style: .medium)
    private let retryButton = UIButton(type: .system)
    var retry: (() -> Void)?
    var failed = false {
        didSet {
            retryButton.isHidden = !failed
            if failed { spinner.stopAnimating() } else { spinner.startAnimating() }
        }
    }

    override init(frame: CGRect) {
        super.init(frame: frame)
        clipsToBounds = true
        backgroundColor = UIColor(white: 0.06, alpha: 1)
        imageView.contentMode = .scaleAspectFit
        addSubview(imageView)
        spinner.color = .yellow
        spinner.startAnimating()
        addSubview(spinner)
        retryButton.setTitle("图片加载失败 · 点击重试", for: .normal)
        retryButton.tintColor = .yellow
        retryButton.isHidden = true
        retryButton.addAction(UIAction { [weak self] _ in self?.retry?() }, for: .touchUpInside)
        addSubview(retryButton)
    }

    required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }

    override func layoutSubviews() {
        super.layoutSubviews()
        imageView.frame = bounds
        spinner.center = CGPoint(x: bounds.midX, y: bounds.midY)
        retryButton.frame = CGRect(x: 0, y: max(0, bounds.midY - 22), width: bounds.width, height: 44)
    }

    func show(_ image: UIImage) {
        imageView.image = image
        spinner.stopAnimating()
        retryButton.isHidden = true
    }
}
